CREATE TABLE CLIENTE(
	ID				UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME			VARCHAR(100)		NOT NULL,
	EMAIL			VARCHAR(50)			NOT NULL,
	CPF				VARCHAR(14)			NOT NULL,
	TIPO			VARCHAR(15)			NOT NULL,
	DATACADASTRO	DATETIME			NOT NULL,
	CHECK(TIPO IN('Comum', 'Preferencial', 'VIP')))
GO

INSERT INTO CLIENTE(ID, NOME, EMAIL, CPF, TIPO, DATACADASTRO)
VALUES
	(NEWID(), 'Ana Maria', 'anamaria@gmail.com', '12345678900', 'Preferencial', GETDATE()),
	(NEWID(), 'João Pedro', 'joaopedro@gmail.com', '32165498700', 'VIP', GETDATE()),
	(NEWID(), 'Ana Paula', 'anapaula@gmail.com', '98765432100', 'Comum', GETDATE())
GO

SELECT ID, NOME, EMAIL, CPF, TIPO, DATACADASTRO
FROM CLIENTE
ORDER BY NOME
GO